[project]
name = 'Decentralized-Identity-and-Credential-System'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.credential-issuance]
path = 'contracts/credential-issuance.clar'
clarity_version = 2
epoch = 2.5

[contracts.identity-verification]
path = 'contracts/identity-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.revocation-registry]
path = 'contracts/revocation-registry.clar'
clarity_version = 2
epoch = 2.5

[contracts.selective-disclosure]
path = 'contracts/selective-disclosure.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
